force-app/main/default/objects/FIFA_Match__c/FIFA_Match__c.object-meta.xml
<CustomObject>
    <description>Stores match data &amp; info.</description>
    <label>Match</label>
    <nameField>
        <displayFormat>Match-{000}</displayFormat>
        <label>Match</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Matches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FIFA_Match__c/fields/FIFA_Match_Winner__c.field-meta.xml
<CustomField>
    <fullName>FIFA_Match_Winner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Auto calculated on save</inlineHelpText>
    <label>Winner</label>
    <referenceTo>FIFA_Player__c</referenceTo>
    <relationshipLabel>Matches Won</relationshipLabel>
    <relationshipName>Matches2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FIFA_Match__c/fields/FIFA_Player_1__c.field-meta.xml
<CustomField>
    <fullName>FIFA_Player_1__c</fullName>
    <label>Player 1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIFA_All_Players</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIFA_Match__c/fields/FIFA_Player_1_Score__c.field-meta.xml
<CustomField>
    <fullName>FIFA_Player_1_Score__c</fullName>
    <label>Player 1 Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FIFA_Match__c/fields/FIFA_Player_2__c.field-meta.xml
<CustomField>
    <fullName>FIFA_Player_2__c</fullName>
    <label>Player 2</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>FIFA_All_Players</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FIFA_Match__c/fields/FIFA_Player_2_Score__c.field-meta.xml
<CustomField>
    <fullName>FIFA_Player_2_Score__c</fullName>
    <label>Player 2 Score</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/FIFA_All_Players.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Kishan</fullName>
    </customValue>
    <customValue>
        <fullName>Rajesh</fullName>
    </customValue>
    <customValue>
        <fullName>Sethuram</fullName>
    </customValue>
    <customValue>
        <fullName>Vignesh</fullName>
    </customValue>
    <description>Contains list of all players who game</description>
    <masterLabel>All Players</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FIFA_Match_Trigger_Helper.cls
// add class description
public with sharing class FIFA_Match_Trigger_Helper {
    // add function description
    public static void preventPlayerDuplicates(List<FIFA_Match__c> matches) {    
        for(FIFA_Match__c match : matches) {
            if(match.FIFA_Player_1__c == match.FIFA_Player_2__c) {
                match.addError('FIFA_Player_2__c', 'Players cannot be the same');
            }
        }
    }
    //  add function comment
    public static void populateMatchWinner(List<FIFA_Match__c> matches) {
        for(FIFA_Match__c match : matches) {
            if(match.FIFA_Player_1_Score__c > match.FIFA_Player_2_Score__c) {
                match.FIFA_Match_Winner__c = match.FIFA_Player_1__c;
            } 
            else if(match.FIFA_Player_1_Score__c < match.FIFA_Player_2_Score__c) {
                match.FIFA_Match_Winner__c = match.FIFA_Player_2__c;
            } 
            else {
                match.FIFA_Match_Winner__c = 'Draw';
            }
        }
    }
}